#!/usr/bin/env python3
"""MCP stdio server for Apache Iceberg REST Catalog API — generated by openapi2mcp.

Run:  python3 lakekeeper_cat_mcp_server.py
Env:  LAKEKEEPER_CAT_TOKEN   bearer token / api key (optional)
      LAKEKEEPER_CAT_BASE_URL  override base URL (default https://localhost)
"""
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

BASE = os.environ.get("LAKEKEEPER_CAT_BASE_URL", "https://localhost").rstrip("/")
TOKEN = os.environ.get("LAKEKEEPER_CAT_TOKEN", "")
AUTH_HEADER = os.environ.get("LAKEKEEPER_CAT_TOKEN_HEADER", "Authorization")
AUTH_PREFIX = os.environ.get("LAKEKEEPER_CAT_TOKEN_PREFIX", "Bearer ")

# P19: embedded as JSON and parsed at runtime, NOT as a Python literal. A schema
# carrying a boolean/null (enum: [false, true], default: null) dumps as `false`/
# `null`, which are not Python names — the server then dies at import with
# `NameError: name 'false' is not defined` before it can answer a single request.
TOOLS = json.loads(r"""
[
    {
        "name": "getconfig",
        "description": "List all catalog configuration settings",
        "inputSchema": {
            "type": "object",
            "properties": {
                "warehouse": {
                    "type": "string",
                    "description": "Warehouse location or identifier to request from the service"
                }
            },
            "required": []
        },
        "_method": "GET",
        "_path": "/v1/config"
    },
    {
        "name": "listnamespaces",
        "description": "List namespaces, optionally providing a parent namespace to list underneath",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "An optional prefix in the path"
                },
                "pageToken": {
                    "type": {}
                },
                "pageSize": {
                    "type": "integer",
                    "description": "For servers that support pagination, this signals an upper bound of the number of results that a client will receive. For servers that do not support pagination, clients may receive results larger tha"
                },
                "parent": {
                    "type": "string",
                    "description": "An optional namespace, underneath which to list namespaces. If not provided, all top-level namespaces should be listed. For backward compatibility, empty string is treated as absent for now. If parent"
                },
                "returnUuids": {
                    "type": "boolean",
                    "description": "If true, include the `namespace-uuids` field in the response"
                },
                "returnProtectionStatus": {
                    "type": "boolean",
                    "description": "If true, include the `protection-status` field in the response"
                }
            },
            "required": [
                "prefix"
            ]
        },
        "_method": "GET",
        "_path": "/v1/{prefix}/namespaces"
    },
    {
        "name": "loadnamespacemetadata",
        "description": "Load the metadata properties for a namespace",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "An optional prefix in the path"
                },
                "namespace": {
                    "type": "string",
                    "description": "A namespace identifier as a single string. Multipart namespace parts must be separated by the namespace separator as indicated via the /config override `namespace-separator`, which defaults to the uni"
                },
                "returnUuid": {
                    "type": "boolean",
                    "description": "If true, include the `namespace-uuid` field in the response"
                }
            },
            "required": [
                "prefix",
                "namespace"
            ]
        },
        "_method": "GET",
        "_path": "/v1/{prefix}/namespaces/{namespace}"
    },
    {
        "name": "listtables",
        "description": "List all table identifiers underneath a given namespace",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "An optional prefix in the path"
                },
                "namespace": {
                    "type": "string",
                    "description": "A namespace identifier as a single string. Multipart namespace parts must be separated by the namespace separator as indicated via the /config override `namespace-separator`, which defaults to the uni"
                },
                "pageToken": {
                    "type": {}
                },
                "pageSize": {
                    "type": "integer",
                    "description": "For servers that support pagination, this signals an upper bound of the number of results that a client will receive. For servers that do not support pagination, clients may receive results larger tha"
                },
                "returnUuids": {
                    "type": "boolean",
                    "description": "If true, include the `table-uuids` field in the response"
                },
                "returnProtectionStatus": {
                    "type": "boolean",
                    "description": "If true, include the `protection-status` field in the response"
                }
            },
            "required": [
                "prefix",
                "namespace"
            ]
        },
        "_method": "GET",
        "_path": "/v1/{prefix}/namespaces/{namespace}/tables"
    },
    {
        "name": "loadtable",
        "description": "Load a table from the catalog",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "An optional prefix in the path"
                },
                "namespace": {
                    "type": "string",
                    "description": "A namespace identifier as a single string. Multipart namespace parts must be separated by the namespace separator as indicated via the /config override `namespace-separator`, which defaults to the uni"
                },
                "table": {
                    "type": "string",
                    "description": "A table name"
                },
                "X-Iceberg-Access-Delegation": {
                    "type": "string",
                    "description": "Optional signal to the server that the client supports delegated access via a comma-separated list of access mechanisms.  The server may choose to supply access via any or none of the requested mechan",
                    "enum": [
                        {},
                        {}
                    ]
                },
                "If-None-Match": {
                    "type": "string",
                    "description": "An optional header that allows the server to return 304 (Not Modified) if the metadata is current. The content is the value of the ETag received in a CreateTableResponse, LoadTableResponse or CommitTa"
                },
                "snapshots": {
                    "type": "string",
                    "description": "The snapshots to return in the body of the metadata. Setting the value to `all` would return the full set of snapshots currently valid for the table. Setting the value to `refs` would load all snapsho",
                    "enum": [
                        "all",
                        "refs"
                    ]
                },
                "referenced-by": {
                    "type": "string",
                    "description": "A comma-separated list of fully qualified view names (namespace and view name) representing the view reference chain when an entity (table or view) is loaded via a view. The list should be ordered wit"
                }
            },
            "required": [
                "prefix",
                "namespace",
                "table"
            ]
        },
        "_method": "GET",
        "_path": "/v1/{prefix}/namespaces/{namespace}/tables/{table}"
    },
    {
        "name": "loadcredentials",
        "description": "Load vended credentials for a table from the catalog",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "An optional prefix in the path"
                },
                "namespace": {
                    "type": "string",
                    "description": "A namespace identifier as a single string. Multipart namespace parts must be separated by the namespace separator as indicated via the /config override `namespace-separator`, which defaults to the uni"
                },
                "table": {
                    "type": "string",
                    "description": "A table name"
                },
                "planId": {
                    "type": "string",
                    "description": "The plan ID that has been used for server-side scan planning"
                },
                "referenced-by": {
                    "type": "string",
                    "description": "A comma-separated list of fully qualified view names (namespace and view name) representing the view reference chain when an entity (table or view) is loaded via a view. The list should be ordered wit"
                }
            },
            "required": [
                "prefix",
                "namespace",
                "table"
            ]
        },
        "_method": "GET",
        "_path": "/v1/{prefix}/namespaces/{namespace}/tables/{table}/credentials"
    },
    {
        "name": "fetchplanningresult",
        "description": "Fetches the result of scan planning for a plan-id",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "An optional prefix in the path"
                },
                "namespace": {
                    "type": "string",
                    "description": "A namespace identifier as a single string. Multipart namespace parts must be separated by the namespace separator as indicated via the /config override `namespace-separator`, which defaults to the uni"
                },
                "table": {
                    "type": "string",
                    "description": "A table name"
                },
                "plan-id": {
                    "type": "string",
                    "description": "ID used to track a planning request"
                },
                "X-Iceberg-Access-Delegation": {
                    "type": "string",
                    "description": "Optional signal to the server that the client supports delegated access via a comma-separated list of access mechanisms.  The server may choose to supply access via any or none of the requested mechan",
                    "enum": [
                        "vended-credentials",
                        "remote-signing"
                    ]
                }
            },
            "required": [
                "prefix",
                "namespace",
                "table",
                "plan-id"
            ]
        },
        "_method": "GET",
        "_path": "/v1/{prefix}/namespaces/{namespace}/tables/{table}/plan/{plan-id}"
    },
    {
        "name": "listviews",
        "description": "List all view identifiers underneath a given namespace",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "description": "An optional prefix in the path"
                },
                "namespace": {
                    "type": "string",
                    "description": "A namespace identifier as a single string. Multipart namespace parts must be separated by the namespace separator as indicated via the /config override `namespace-separator`, which defaults to the uni"
                },
                "pageToken": {
                    "type": {}
                },
                "pageSize": {
                    "type": "integer",
                    "description": "For servers that support pagination, this signals an upper bound of the number of results that a client will receive. For servers that do not support pagination, clients may receive results larger tha"
                },
                "returnUuids": {
                    "type": "boolean",
                    "description": "If true, include the `table-uuids` field in the response"
                },
                "returnProtectionStatus": {
                    "type": "boolean",
                    "description": "If true, include the `protection-status` field in the response"
                }
            },
            "required": [
                "prefix",
                "namespace"
            ]
        },
        "_method": "GET",
        "_path": "/v1/{prefix}/namespaces/{namespace}/views"
    }
]
""")

SPECS = {t["name"]: t for t in TOOLS}


def _call_api(spec, args):
    path = spec["_path"]
    query = {}
    body = args.get("body")
    for key, val in (args or {}).items():
        if key == "body":
            continue
        token = "{" + key + "}"
        if token in path:
            path = path.replace(token, urllib.parse.quote(str(val), safe=""))
        else:
            query[key] = val
    url = BASE + path
    if query:
        url += "?" + urllib.parse.urlencode(query, doseq=True)
    data = None
    headers = {"Accept": "application/json", "User-Agent": "lakekeeper_cat_mcp_server/1.0"}
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    if TOKEN:
        headers[AUTH_HEADER] = AUTH_PREFIX + TOKEN
    req = urllib.request.Request(url, data=data, headers=headers, method=spec["_method"])
    try:
        with urllib.request.urlopen(req, timeout=45) as resp:
            payload = resp.read().decode("utf-8", "replace")
            return f"HTTP {resp.status}\n{payload[:20000]}"
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace")[:4000]
        return f"HTTP {exc.code} {exc.reason}\n{detail}"
    except Exception as exc:  # network, DNS, timeout
        return f"ERROR calling {spec['_method']} {url}: {exc}"


def _public(tool):
    return {k: v for k, v in tool.items() if not k.startswith("_")}


def handle(msg):
    method = msg.get("method")
    mid = msg.get("id")
    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": mid,
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {}},
                "serverInfo": {"name": "lakekeeper_cat_mcp_server", "version": "1.0.0"},
            },
        }
    if method in ("notifications/initialized", "initialized"):
        return None
    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": mid, "result": {"tools": [_public(t) for t in TOOLS]}}
    if method == "tools/call":
        params = msg.get("params") or {}
        spec = SPECS.get(params.get("name"))
        if spec is None:
            return {"jsonrpc": "2.0", "id": mid,
                    "error": {"code": -32602, "message": f"unknown tool {params.get('name')}"}}
        text = _call_api(spec, params.get("arguments") or {})
        is_err = text.startswith("ERROR") or text.startswith("HTTP 4") or text.startswith("HTTP 5")
        return {"jsonrpc": "2.0", "id": mid,
                "result": {"content": [{"type": "text", "text": text}], "isError": is_err}}
    if mid is None:
        return None
    return {"jsonrpc": "2.0", "id": mid, "error": {"code": -32601, "message": f"unknown method {method}"}}


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        out = handle(msg)
        if out is not None:
            sys.stdout.write(json.dumps(out) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
