#!/usr/bin/env python3
"""MCP stdio server for OWASP Dependency-Track — generated by openapi2mcp.

Run:  python3 deptrack_mcp_server.py
Env:  DEPTRACK_TOKEN   bearer token / api key (optional)
      DEPTRACK_BASE_URL  override base URL (default /api/v2)
"""
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

BASE = os.environ.get("DEPTRACK_BASE_URL", "/api/v2").rstrip("/")
TOKEN = os.environ.get("DEPTRACK_TOKEN", "")
AUTH_HEADER = os.environ.get("DEPTRACK_TOKEN_HEADER", "Authorization")
AUTH_PREFIX = os.environ.get("DEPTRACK_TOKEN_PREFIX", "Bearer ")

TOOLS = [
    {
        "name": "listcomponents",
        "description": "List all components",
        "inputSchema": {
            "type": "object",
            "properties": {
                "group_contains": {
                    "type": "string",
                    "description": "Filter by group (substring match)"
                },
                "name_contains": {
                    "type": "string",
                    "description": "Filter by name (substring match)"
                },
                "version_contains": {
                    "type": "string",
                    "description": "Filter by version (substring match)"
                },
                "purl_prefix": {
                    "type": "string",
                    "description": "Filter by PURL (prefix match).\n\nMust be a valid PURL, with at least `pkg:<ecosystem>/<name>` populated."
                },
                "cpe": {
                    "type": "string",
                    "description": "Filter by CPE (exact match).\n\nMust be a valid CPE."
                },
                "swid_tag_id_contains": {
                    "type": "string",
                    "description": "Filter by SWID Tag ID (substring match)"
                },
                "hash_type": {
                    "type": "string",
                    "description": "The hash type to filter by",
                    "enum": [
                        "MD5",
                        "SHA1",
                        "SHA_256",
                        "SHA_384",
                        "SHA_512",
                        "SHA3_256",
                        "SHA3_384",
                        "SHA3_512",
                        "BLAKE2B_256",
                        "BLAKE2B_384",
                        "BLAKE2B_512",
                        "BLAKE3",
                        "STREEBOG_256",
                        "STREEBOG_512"
                    ]
                },
                "hash": {
                    "type": "string",
                    "description": "Filter by hash value (exact match).\n\nRequires `hash_type` to be set."
                },
                "package_artifact_published_since": {
                    "type": "integer",
                    "description": "Filter by package artifact publish date (inclusive lower bound).\n\nNote that components without resolved package artifact metadata,\nor whose upstream repository did not report a publication date,\nare e"
                },
                "package_artifact_published_before": {
                    "type": "integer",
                    "description": "Filter by package artifact publish date (exclusive upper bound)."
                },
                "project_state": {
                    "type": "string",
                    "description": "Filter by the state of the project that the component belongs to.\n\nOmit to include components from projects in any state.",
                    "enum": [
                        "ACTIVE",
                        "INACTIVE"
                    ]
                },
                "project_latest_version": {
                    "type": "boolean",
                    "description": "Filter by whether the project the component belongs to is flagged as the latest version.\n\nWhen `true`, only components from latest-version projects are returned.\nWhen `false`, only components from non"
                },
                "expand": {
                    "type": "array",
                    "description": "Optional fields to include in each component response item. Unknown values are silently ignored."
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of items to retrieve from the collection"
                },
                "page_token": {
                    "type": "string",
                    "description": "Opaque token pointing to a specific position in a collection"
                },
                "sort_direction": {
                    "type": "string",
                    "enum": [
                        "ASC",
                        "DESC"
                    ]
                },
                "sort_by": {
                    "type": "string",
                    "description": "Field to sort by. Refer to the operation description for information about which fields are sortable."
                }
            },
            "required": []
        },
        "_method": "GET",
        "_path": "/components"
    },
    {
        "name": "listprojectcomponents",
        "description": "Retrieves a list of all components for a given project.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string",
                    "description": "The UUID of the project to retrieve components for"
                },
                "only_outdated": {
                    "type": "boolean",
                    "description": "Optionally exclude recent components so only outdated components are returned"
                },
                "only_direct": {
                    "type": "boolean",
                    "description": "Optionally exclude transitive dependencies so only direct dependencies are returned"
                },
                "q": {
                    "type": "string",
                    "description": "Optional free-text search term. Matches components whose `group` or `name` contains the given value (case-insensitive)."
                },
                "expand": {
                    "type": "array",
                    "description": "Optional fields to include in each component response item. Unknown values are silently ignored."
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of items to retrieve from the collection"
                },
                "page_token": {
                    "type": "string",
                    "description": "Opaque token pointing to a specific position in a collection"
                },
                "sort_direction": {
                    "type": "string",
                    "enum": [
                        "ASC",
                        "DESC"
                    ]
                },
                "sort_by": {
                    "type": "string",
                    "description": "Field to sort by. Refer to the operation description for information about which fields are sortable."
                }
            },
            "required": [
                "uuid"
            ]
        },
        "_method": "GET",
        "_path": "/projects/{uuid}/components"
    },
    {
        "name": "getlatestvulndatasourcemirrorrun",
        "description": "Get the latest vulnerability data source mirror run",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the vulnerability data source (e.g. `nvd`, `osv`, `github`)."
                }
            },
            "required": [
                "name"
            ]
        },
        "_method": "GET",
        "_path": "/vuln-data-sources/{name}/mirror-runs/latest"
    },
    {
        "name": "listvulnpolicies",
        "description": "List vulnerability policies",
        "inputSchema": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of items to retrieve from the collection"
                },
                "page_token": {
                    "type": "string",
                    "description": "Opaque token pointing to a specific position in a collection"
                },
                "name": {
                    "type": "string",
                    "description": "Filter by name (partial match, case-insensitive)"
                }
            },
            "required": []
        },
        "_method": "GET",
        "_path": "/vuln-policies"
    },
    {
        "name": "getvulnpolicy",
        "description": "Get a vulnerability policy",
        "inputSchema": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string",
                    "description": "UUID of the vulnerability policy"
                }
            },
            "required": [
                "uuid"
            ]
        },
        "_method": "GET",
        "_path": "/vuln-policies/{uuid}"
    },
    {
        "name": "listvulnpolicybundles",
        "description": "List vulnerability policy bundles",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        },
        "_method": "GET",
        "_path": "/vuln-policy-bundles"
    },
    {
        "name": "getlatestvulnpolicybundlesyncrun",
        "description": "Get the latest vulnerability policy bundle sync run",
        "inputSchema": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string",
                    "description": "UUID of the vulnerability policy bundle"
                }
            },
            "required": [
                "uuid"
            ]
        },
        "_method": "GET",
        "_path": "/vuln-policy-bundles/{uuid}/sync-runs/latest"
    },
    {
        "name": "listvulnkevassertions",
        "description": "Lists KEV assertions for a vulnerability",
        "inputSchema": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string",
                    "description": "Source of the vulnerability (e.g. `NVD`, `GITHUB`, `OSV`)."
                },
                "vuln_id": {
                    "type": "string",
                    "description": "Identifier of the vulnerability (e.g. `CVE-2021-44228`)."
                }
            },
            "required": [
                "source",
                "vuln_id"
            ]
        },
        "_method": "GET",
        "_path": "/vulns/{source}/{vuln_id}/kev-assertions"
    }
]

SPECS = {t["name"]: t for t in TOOLS}


def _call_api(spec, args):
    path = spec["_path"]
    query = {}
    body = args.get("body")
    for key, val in (args or {}).items():
        if key == "body":
            continue
        token = "{" + key + "}"
        if token in path:
            path = path.replace(token, urllib.parse.quote(str(val), safe=""))
        else:
            query[key] = val
    url = BASE + path
    if query:
        url += "?" + urllib.parse.urlencode(query, doseq=True)
    data = None
    headers = {"Accept": "application/json", "User-Agent": "deptrack_mcp_server/1.0"}
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    if TOKEN:
        headers[AUTH_HEADER] = AUTH_PREFIX + TOKEN
    req = urllib.request.Request(url, data=data, headers=headers, method=spec["_method"])
    try:
        with urllib.request.urlopen(req, timeout=45) as resp:
            payload = resp.read().decode("utf-8", "replace")
            return f"HTTP {resp.status}\n{payload[:20000]}"
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace")[:4000]
        return f"HTTP {exc.code} {exc.reason}\n{detail}"
    except Exception as exc:  # network, DNS, timeout
        return f"ERROR calling {spec['_method']} {url}: {exc}"


def _public(tool):
    return {k: v for k, v in tool.items() if not k.startswith("_")}


def handle(msg):
    method = msg.get("method")
    mid = msg.get("id")
    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": mid,
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {}},
                "serverInfo": {"name": "deptrack_mcp_server", "version": "1.0.0"},
            },
        }
    if method in ("notifications/initialized", "initialized"):
        return None
    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": mid, "result": {"tools": [_public(t) for t in TOOLS]}}
    if method == "tools/call":
        params = msg.get("params") or {}
        spec = SPECS.get(params.get("name"))
        if spec is None:
            return {"jsonrpc": "2.0", "id": mid,
                    "error": {"code": -32602, "message": f"unknown tool {params.get('name')}"}}
        text = _call_api(spec, params.get("arguments") or {})
        is_err = text.startswith("ERROR") or text.startswith("HTTP 4") or text.startswith("HTTP 5")
        return {"jsonrpc": "2.0", "id": mid,
                "result": {"content": [{"type": "text", "text": text}], "isError": is_err}}
    if mid is None:
        return None
    return {"jsonrpc": "2.0", "id": mid, "error": {"code": -32601, "message": f"unknown method {method}"}}


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        out = handle(msg)
        if out is not None:
            sys.stdout.write(json.dumps(out) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
