#!/usr/bin/env python3
"""MCP stdio server for PostHog API — generated by openapi2mcp.

Run:  python3 posthog_mcp_server.py
Env:  POSTHOG_TOKEN   bearer token / api key (optional)
      POSTHOG_BASE_URL  override base URL (default https://app.posthog.com)
"""
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

BASE = os.environ.get("POSTHOG_BASE_URL", "https://app.posthog.com").rstrip("/")
TOKEN = os.environ.get("POSTHOG_TOKEN", "")
AUTH_HEADER = os.environ.get("POSTHOG_TOKEN_HEADER", "Authorization")
AUTH_PREFIX = os.environ.get("POSTHOG_TOKEN_PREFIX", "Bearer ")

# P19: embedded as JSON and parsed at runtime, NOT as a Python literal. A schema
# carrying a boolean/null (enum: [false, true], default: null) dumps as `false`/
# `null`, which are not Python names — the server then dies at import with
# `NameError: name 'false' is not defined` before it can answer a single request.
TOOLS = json.loads(r"""
[
    {
        "name": "code_invites_check_access_retrieve",
        "description": "Check access",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        },
        "_method": "GET",
        "_path": "/api/code/invites/check-access/"
    },
    {
        "name": "code_sandbox_pricing_list",
        "description": "Get sandbox compute pricing",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        },
        "_method": "GET",
        "_path": "/api/code/sandbox-pricing/"
    },
    {
        "name": "customer_analytics_external_accounts_retrieve",
        "description": "List external customer analytics accounts",
        "inputSchema": {
            "type": "object",
            "properties": {
                "assigned_only": {
                    "type": "boolean",
                    "description": "When true, return only accounts with at least one active relationship assignment to a current member of the project's organization."
                },
                "cursor": {
                    "type": "string",
                    "description": "Account UUID from `next_cursor` to continue listing from. Omit for the first page."
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of accounts to return. Values below 1 are clamped to 1; values above 100 are clamped to 100."
                }
            },
            "required": []
        },
        "_method": "GET",
        "_path": "/api/customer_analytics/external/accounts"
    },
    {
        "name": "llm_analytics_personal_spend_list",
        "description": "Return a structured personal LLM spend analysis for the requesting user. Pass `date_from` / `date_to` (absolute like `2026-04-23` or relative like `-7d`) to bound the window \u2014 defaults to the last 30 days, max 90 days. The `product=<ai_product>` query param is required and scopes the tool / model / ",
        "inputSchema": {
            "type": "object",
            "properties": {
                "bucket_minutes": {
                    "type": "integer",
                    "description": "When set, additionally return a `by_bucket` breakdown: a time-ascending UTC cost series for the scoped product at this bucket size in minutes, with per-bucket cost split into uncached input / output /",
                    "enum": [
                        5,
                        15,
                        30,
                        60
                    ]
                },
                "date_from": {
                    "type": "string",
                    "description": "Start of the spend window. Accepts absolute dates (`2026-04-23`) or relative strings (`-7d`, `-1m`, etc.) \u2014 same parser used elsewhere in PostHog. Defaults to `-30d`. The window between `date_from` an"
                },
                "date_to": {
                    "type": [
                        "string",
                        "null"
                    ],
                    "description": "End of the spend window. Accepts the same formats as `date_from`. Defaults to `now` when omitted."
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of rows to return per breakdown (1-200, defaults to 50). Each breakdown returns up to this many rows ordered by cost descending. Per-breakdown `truncated: true` indicates more rows exis"
                },
                "product": {
                    "type": "string",
                    "description": "Required `ai_product` key to scope the tool / model / trace breakdowns to a single product. Only the following products are currently supported: posthog_code."
                },
                "refresh": {
                    "type": "boolean",
                    "description": "If true, bypass the result cache and re-run the underlying queries against ClickHouse."
                }
            },
            "required": [
                "product"
            ]
        },
        "_method": "GET",
        "_path": "/api/llm_analytics/@me/spend/"
    },
    {
        "name": "list",
        "description": "GET /api/organizations/",
        "inputSchema": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "description": "Number of results to return per page."
                },
                "offset": {
                    "type": "integer",
                    "description": "The initial index from which to return the results."
                }
            },
            "required": []
        },
        "_method": "GET",
        "_path": "/api/organizations/"
    },
    {
        "name": "retrieve",
        "description": "GET /api/organizations/{id}/",
        "inputSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "A UUID string identifying this organization."
                }
            },
            "required": [
                "id"
            ]
        },
        "_method": "GET",
        "_path": "/api/organizations/{id}/"
    },
    {
        "name": "teams_data_freshness_retrieve",
        "description": "When each project in the organization last received data, broken down by kind of data.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "A UUID string identifying this organization."
                }
            },
            "required": [
                "id"
            ]
        },
        "_method": "GET",
        "_path": "/api/organizations/{id}/teams/data_freshness/"
    },
    {
        "name": "billing_alerts_list",
        "description": "GET /api/organizations/{organization_id}/billing/alerts/",
        "inputSchema": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "description": "Number of results to return per page."
                },
                "offset": {
                    "type": "integer",
                    "description": "The initial index from which to return the results."
                },
                "organization_id": {
                    "type": "string",
                    "description": "ID of the organization you're trying to access. To find the ID of the organization, make a call to /api/organizations/."
                }
            },
            "required": [
                "organization_id"
            ]
        },
        "_method": "GET",
        "_path": "/api/organizations/{organization_id}/billing/alerts/"
    }
]
""")

SPECS = {t["name"]: t for t in TOOLS}


def _call_api(spec, args):
    path = spec["_path"]
    query = {}
    body = args.get("body")
    for key, val in (args or {}).items():
        if key == "body":
            continue
        token = "{" + key + "}"
        if token in path:
            path = path.replace(token, urllib.parse.quote(str(val), safe=""))
        else:
            query[key] = val
    url = BASE + path
    if query:
        url += "?" + urllib.parse.urlencode(query, doseq=True)
    data = None
    headers = {"Accept": "application/json", "User-Agent": "posthog_mcp_server/1.0"}
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    if TOKEN:
        headers[AUTH_HEADER] = AUTH_PREFIX + TOKEN
    req = urllib.request.Request(url, data=data, headers=headers, method=spec["_method"])
    try:
        with urllib.request.urlopen(req, timeout=45) as resp:
            payload = resp.read().decode("utf-8", "replace")
            return f"HTTP {resp.status}\n{payload[:20000]}"
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace")[:4000]
        return f"HTTP {exc.code} {exc.reason}\n{detail}"
    except Exception as exc:  # network, DNS, timeout
        return f"ERROR calling {spec['_method']} {url}: {exc}"


def _public(tool):
    return {k: v for k, v in tool.items() if not k.startswith("_")}


def handle(msg):
    method = msg.get("method")
    mid = msg.get("id")
    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": mid,
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {}},
                "serverInfo": {"name": "posthog_mcp_server", "version": "1.0.0"},
            },
        }
    if method in ("notifications/initialized", "initialized"):
        return None
    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": mid, "result": {"tools": [_public(t) for t in TOOLS]}}
    if method == "tools/call":
        params = msg.get("params") or {}
        spec = SPECS.get(params.get("name"))
        if spec is None:
            return {"jsonrpc": "2.0", "id": mid,
                    "error": {"code": -32602, "message": f"unknown tool {params.get('name')}"}}
        text = _call_api(spec, params.get("arguments") or {})
        is_err = text.startswith("ERROR") or text.startswith("HTTP 4") or text.startswith("HTTP 5")
        return {"jsonrpc": "2.0", "id": mid,
                "result": {"content": [{"type": "text", "text": text}], "isError": is_err}}
    if mid is None:
        return None
    return {"jsonrpc": "2.0", "id": mid, "error": {"code": -32601, "message": f"unknown method {method}"}}


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        out = handle(msg)
        if out is not None:
            sys.stdout.write(json.dumps(out) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
